# Generated by Django 4.1.6 on 2023-02-16 14:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buisnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=50)),
                ('company_website', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('buisness_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('buisness_description', models.CharField(blank=True, max_length=100)),
                ('buisness_images', models.ImageField(blank=True, upload_to='')),
                ('other_details', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=5)),
                ('review', models.CharField(blank=True, max_length=50)),
                ('review_images', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
