# Generated by Django 4.1.6 on 2023-02-21 19:38

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import webapiapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buisnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed.'), webapiapp.models.length_name])),
                ('company_website', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(https:\\/\\/www\\.|http:\\/\\/www\\.|www\\.)[a-zA-Z0-9]+\\.[a-zA-Z]{2,5}$', 'enter a valid url')])),
                ('address', models.CharField(max_length=100, validators=[webapiapp.models.address_length])),
                ('state', models.CharField(blank=True, max_length=50)),
                ('buisness_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, validators=[webapiapp.models.phone_number])),
                ('email', models.EmailField(max_length=254, null=True)),
                ('buisness_description', models.CharField(blank=True, max_length=1000)),
                ('buisness_images', models.FileField(blank=True, null=True, upload_to='files')),
                ('other_details', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
