# Generated by Django 4.1.6 on 2023-02-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisnessprofile',
            name='phone_num',
            field=models.BigIntegerField(),
        ),
    ]
