# Generated by Django 4.1.6 on 2023-02-14 14:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webapiapp', '0002_alter_buisnessprofile_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisnessprofile',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
