# Generated by Django 4.1.6 on 2023-02-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapiapp', '0003_alter_buisnessprofile_buisness_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisnessprofile',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='buisnessprofile',
            name='buisness_description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='buisnessprofile',
            name='other_details',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='buisnessprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
